name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v5
      - name: Step level example
        env:
          CITY: Hyderabad
          TRAINER: Balaji Reddy
        run: |
          echo "City is $CITY"
          echo "Trainer is $TRAINER"
      - name: Next step
        run: echo "City is $CITY and Trainer is $TRAINER"
      - name: Printing Some Default Varaibles
        run: echo "Gihub Repo $GITHUB_REPOSITORY Gihub Ref $GITHUB_REF  Github Commit $GITHUB_SHA"
       